'use strict'

const PROFILE_NAMES = ['live', 'liveeu', 'pts']
const BUNDLED_ADDON_VERSION = '1.0.0'
const ADDON_FOLDER = 'ArrowToTheBuild'
const BRIDGE_ADDON_FOLDER = 'ArrowToTheBuildBridge'
const SAVED_VARIABLES_FILE = 'ArrowToTheBuild.lua'
const BRIDGE_SAVED_VARIABLES_FILE = 'ArrowToTheBuildBridge.lua'
const BRIDGE_SAVED_VARIABLE_NAME = 'ArrowToTheBuildBridgeSavedVariables'
const BRIDGE_SCHEMA_VERSION = 2
const ESO_NORMAL_SAVE_LIMIT_BYTES = 50 * 1024
const REPOSITORY_URL = 'https://github.com/DeadxxSmile/Arrow-to-the-Build-ESO-Addon'

module.exports = {
  PROFILE_NAMES, BUNDLED_ADDON_VERSION, ADDON_FOLDER, BRIDGE_ADDON_FOLDER,
  SAVED_VARIABLES_FILE, BRIDGE_SAVED_VARIABLES_FILE, BRIDGE_SAVED_VARIABLE_NAME,
  BRIDGE_SCHEMA_VERSION, ESO_NORMAL_SAVE_LIMIT_BYTES, REPOSITORY_URL
}
